language: python
python:
  - "2.7"
  - "3.5"
cache: pip
before_install:
  - "pip install -U pip"
  - "export PYTHONPATH=$PYTHONPATH:$(pwd)"
install:
  - pip install -r requirements.txt
script:
  - py.test
